services:
  db:
    image: mysql:8.0.36
    container_name: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=webapp07
      - MYSQL_DATABASE=mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  web:
    image: hugost010/volteretacroqueta:latest
    container_name: volteretacroqueta-app
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=webapp07
    depends_on:
      db:
        condition: service_healthy