export enum Allergens {
  GLUTEN = 'GLUTEN',
  CRUSTACEANS = 'CRUSTACEANS',
  EGGS = 'EGGS',
  FISH = 'FISH',
  PEANUTS = 'PEANUTS',
  SOYBEANS = 'SOYBEANS',
  MILK = 'MILK',
  NUTS = 'NUTS',
  CELERY = 'CELERY',
  MUSTARD = 'MUSTARD',
  SESAME_SEEDS = 'SESAME_SEEDS',
  SULPHITES = 'SULPHITES',
  LUPIN = 'LUPIN',
  MOLLUSCS = 'MOLLUSCS'
}
